# Name of workflow
name: Node CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main  # Укажите нужную ветку
  pull_request:

env:
  CI: true

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [18.x]

    steps:
      # Check-out repository under GitHub workspace
      - uses: actions/checkout@v3
      
      # Configures the node version used on GitHub-hosted runners
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: make install

      # Run linter
      - name: Run lint
        run: make lint

      # Run tests
      - name: Run tests
        run: make test

      # Publish code coverage on Code Climate
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        with:
          coverageCommand: make test-coverage
        env:
          CI: true
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
